- .openzeppelin/staging.json
- .openzeppelin/testnet.json
- contracts/Registry.sol
- package-lock.json
- package.json
- scripts/deploy.ts
- scripts/upgrade.ts
- test/index.ts
- test/proxy.ts
Signed-off-by: Carson Farmer <carson.farmer@gmail.com>
This PR adds support for two contracts deployed to rinkeby testnet. There is some manual fiddling about to get this to work, so beware if you want to do upgrades or deployments for individual instances.
Essentially, we have to manage the "history" of the upgrades over time. This is done automatically via open zeppelin tooling, but we have to be careful because we have multiple deployments of the same contract to rinkeby (the norm is to have just one per network).
I've added some new tests to make sure that we can a) mutate the baseURI, and b) deploy the same contract twice with different addresses.
> Support for two contracts + mutable baseURI

- LICENSE
- README.md
- package-lock.json
- package.json
Renames the npm package to the `@tableland` scope. Additionally changes to a contributors list, and renames some of the underlying deps. This should be merged before the corresponding changes to `tablelandnetwork/js-tableland` have been made.
For reviewers, please make sure the npm stuff is scoped to `@tableland`, whereas all the GitHub stuff is scoped to `@tablelandnetwork`.
> feat: update name to @tableland scope

- package-lock.json
- package.json
The js-tableland build fails because we weren't publishing proxies.d.ts and proxies.ts.  `npm link` makes those available so I didn't notice until I did the actual publish
> publish declaration files for proxies.js

- contracts/TablelandTables.sol
- proxies.d.ts.map
- test/TablelandTables.ts
This fixes an issue with the authorization checks that prevents the Validator from relaying calls to `setController` and `lockController`
> Fix check for setController and lockController

- contracts/utils/SQLHelpers.sol
- test/utils/SQLHelpers.ts
The SDK and CLI take params `schema` and `prefix` in that order -- thus, this helper should do the same. The current method params are `toCreateFromSchema(string memory prefix, string memory schema)`, so this PR just flips them and reflects this in the associated hardhat test script.
> refactor: update 'toCreateFromSchema'

- package-lock.json
- package.json
- scripts/deploy.ts
These changes so that we publish the deploy script to npm so that local tableland can use it during start up without cloning this entire repo.   There's also a small change so that the proxy contract address logging is sent to stdout instead of stderr.  Sending it to stderr was crashing the deployment subprocess of local-tableland.
> Publish the deploy script to npm

- .gitignore
- package-lock.json
- package.json
- tsconfig.build.json
In order for the local-tableland npm module `@tableland/local` to include this module as a dependency, then import and run the script to deploy the registry contract we need to transpile and publish the hardhat config as well as the deploy script.
> Update build and publish files for local-tableland

- package-lock.json
- package.json
Use the prepublishOnly script to automatically build before publishing via `npm publish`
> Run build in prepublishOnly script

- network.ts
- package-lock.json
- package.json
This will set the default registry address for a local hardhat network to the value for local-tableland's registry.
After some discussion and usage feedback it seems that this will alleviate some headaches and boiler plate code for devs and automated testing.
> Add local-tableland registry contract address

- package.json
This is a fix for https://github.com/tablelandnetwork/js-tableland/issues/355
This package is publishing source map files but not the source.  This causes warnings in consumers like React Apps.  We can potentially remove the map files, but our other packages publish maps and source so it seems natural to do that here.
cc: @carsonfarmer @dtbuchholz
> fix missing source from published files

- contracts/TablelandTables.sol
- contracts/test/TestTablelandTablesNoConstructor.sol
- package.json
- scripts/initialize.ts
- test/unit/ITablelandController.ts
- test/unit/TablelandTables.ts
- test/unit/TablelandTablesProxy.ts
See here for description of the issue: https://forum.openzeppelin.com/t/uupsupgradeable-vulnerability-post-mortem/15680.
See here for use of _disableInitializers: https://forum.openzeppelin.com/t/what-does-disableinitializers-function-mean/28730/2
See here for method def: https://docs.openzeppelin.com/contracts/4.x/api/proxy#Initializable-_disableInitializers--.
A hotfix for the core issues was added in Contracts 4.3.2 (https://forum.openzeppelin.com/t/uupsupgradeable-vulnerability-post-mortem/15680#hotfix-4). Our contracts are all > 4.5.0. Contracts 4.6.0 added _disableInitializers which removes the ability to call initialize on implementations, even though it's not really an issue anymore.
The usage here is taken from the OZ contract wizard.
> add constructor with call to _disableInitializers

- contracts/TablelandTables.sol
- Cache frequently accessed function param in `for` loops
- Switch `i` to unchecked as it'll always be less than `statements.length` which is checked.
- Use `>=` instead of `>` as it is cheaper.
Prev
| Contract          | Method | Min   | Max   | Avg   | # calls |
|-------------------|--------|-------|-------|-------|---------|
| TablelandTables   | create | 99446 | 114046| 106746| 4       | 
|  TablelandTables  | mutate | 58652 | 62652 | 59985 | 6       |
New
| Contract          | Method | Min   | Max   | Avg    | # calls |
|-------------------|--------|-------|-------|--------|---------|
| TablelandTables   | create | 99315 | 113915| 106615 | 4       |
|  TablelandTables  | mutate | 58515 | 62515 | 59848  | 6       |
Diff
| Contract          | Method | Min Diff | Max Diff | Avg Diff | # …
> Gas Optimizations

- .openzeppelin/goerli.json
- .openzeppelin/mainnet.json
- .openzeppelin/optimism-goerli.json
- .openzeppelin/optimism.json
- .openzeppelin/polygon-mumbai.json
- .openzeppelin/polygon.json
- .openzeppelin/unknown-314.json
- .openzeppelin/unknown-3141.json
- .openzeppelin/unknown-42161.json
- .openzeppelin/unknown-421613.json
- .openzeppelin/unknown-42170.json
- README.md
- package.json
- Upgrades all deployments
- All implementations verified, with the exception of arbitrum-nova. I'm getting this error:
```
Error 1: Failed to verify implementation contract at {my contract address}: The Etherscan API responded with a failure status.
The verification may still succeed but should be checked manually.
Reason: Fail - Unable to verify. Invalid or not supported solc version, see https://etherscan.io/solcversions for list
```
However, if I go to https://etherscan.io/solcversions or https://nova.arbiscan.io/solcversions, the compiler version is listed (0.8.19). I have asked the Arbitrum team for help in their discord.
> ship-3b: upgrade contracts

- hardhat.config.ts
This PR in combination with https://github.com/tablelandnetwork/local-tableland/pull/296 enables a local dev network to deploy the contract regardless of contract size.  This is useful as a means to explore size limitations and underlying issues that affect the deployed contract's size.
> allow setting `allowUnlimitedContractSize` via env

- network.ts
The current `baseURI` value for `filecoin-hyperspace` points to the mainnets gateway, not testnets, which also affects downstream clients like the SDK's `isTestnet` utility method and others.
Idk all of the implications as I wanted to get this out quickly, but I'd assume SDK / CLI methods that try to use Hyperspace will have issues when reading from the wrong gateway. Note that our FVM hackathon is starting next week, and I have a Hyperspace demo _tomorrow_.
Using `npm run test`.
> fix: base URI for Filecoin Hyperspace

- .github/workflows/publish.yml
fix #414 
Update actions that were using node v12 to the most recent which use node 16. This also explicitly runs build the command in hopes it will fix the "Cannot find module '../typechain-types'" error.
> update publish workflow action versions

- package-lock.json
- package.json
The `SQLHelpers` contract depends on @openzeppelin/contracts/utils/Strings.sol so I think we should list that as a dependency, not just a dev dependency.
As a package consumer I would expect that I should be able to
```
npm install @tableland/evm
```
and then
```solidity
import "@tableland/evm/contracts/utils/SQLHelpers.sol";
```
in my contract without errors
> Move @openzeppelin/contracts from being a devDependency to a dependency

- test/unit/ITablelandController.ts
Swaps out `runSQL` for `mutate` in tests.
N/A
`npm run test`
> test: update 'runSQL' to 'mutate'

- contracts/utils/TablelandDeployments.sol
Alters `TablelandDeployments` to use a wrapper/interface around the `ITablelandTables` and `IERC721AUpgradeable` contracts, enabling the same functionality while resolving potential dependency issues. Originally noted [here](https://discord.com/channels/592843512312102924/1182526235511902240/1182760451034071090) and [here](https://discord.com/channels/592843512312102924/1049526583452512359/1187408350049226792) (happened to at least two developers).
Currently, the `TablelandDeployments` contract imports `TablelandTables`, which is an OpenZeppelin `OwnableUpgradeable` contract. This can cause issues because, for example, Remix installs dependencies but doesn't resolve peer-dependencies by grabbing the version the first library depends on—it just resolves to the latest version. With OZ's v5 …
> fix: use interface over imported registry in deployments helper

- package-lock.json
- package.json
- Installs & updates lock file
- Updates package.json to state Node 18 or above is required (previously was 16 before new Hardhat changes).
N/A
N/A
> chore: update node version | bump package-lock.json

- package-lock.json
- package.json
Ethers is currently a devDep, but in order to build with typescript this package must have the correct ethers version. This means any package using this and a different version of ethers will not build correctly.
A user reported an issue using ethers v5 and v6 in the same packages here: https://discord.com/channels/592843512312102924/968582612945870878/1242050427982315645
The fix involves publishing a version of this package with ethers as a dep, and then publishing a version of the sdk that uses the new version of this package.  
If anyone wants to test this out, I published `next` tagged versions for both today.
https://www.npmjs.com/package/@tableland/sdk?activeTab=versions
https://www.npmjs.com/package/@tableland/evm?activeTab=versions
The user who reported the issue has a small test …
> mark ethers as a package dependency

- .prettierrc.json
While reviewing a PR I noticed that we have the prettier Solidity plugin installed, but it isn't being used by prettier.
This adds the plugin to the prettier config.
> add the solidity plugin to the prettier config
